### ISSUE TITLE
vercel部署报错

### ISSUE THREAD

**Issue by zhugezifang** [yanggggjie/rising-repo#2]
vercel部署报错

**Comment by yanggggjie** [comment]
<img width="314" alt="image" src="https://github.com/yanggggjie/rising-repo/assets/60206592/6732dd16-9bbb-4b3c-878d-033bcb1d16b9">
这个可能是vercel部署的时候，没能正确获取到数据
在客户端渲染表格的时候，导致的length为null

还有更多信息吗？

**Comment by zhugezifang** [comment]
我直接fork 你的代码，没有添加东西呢

**Comment by zhugezifang** [comment]
可加下微信zhugezifang001 ，我们沟通下呢

**Comment by yanggggjie** [comment]
已经更新了Readme,添加dev和deploy部分
